FROM python:3.12

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . /app

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

CMD [ "python", "FlaskPoseDetection.py"]