
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

  worker:
    build: Worker
    container_name: worker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mynetwork

  webscraper:
    build: WebScraper
    container_name: webscraper
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data: