services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

  worker:
    build: Worker
    container_name: worker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mynetwork

  webscraper:
    build: WebScraper
    container_name: webscraper
    networks:
      - mynetwork

  frontend:
    build: 
      context: ./StyleMe
      tags:
        - "stran9682/frontend:latest"
    container_name: frontend
    image: stran9682/frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - worker
    networks:
      - mynetwork

    
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 frontend

networks:
  mynetwork:

volumes:
  postgres_data: